import { ClerkProvider } from '@clerk/nextjs/app-beta'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import {Toaster} from "react-hot-toast"
import TopBar from '@/components/shared/Topbar'
import BottomBar from '@/components/shared/Bottombar'
import LeftSidebar from '@/components/shared/Leftbar'
import RightSidebar from '@/components/shared/Rightbar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">

      <body className={inter.className}>
      <div><Toaster/></div>
        <TopBar/>
        <main className='flex flex-row'>
          <LeftSidebar/>
           <section className='main-container'>
            <div className="w-full max-w-4xl">
            {children}
            </div>
           
           </section>

          <RightSidebar/>
        </main>

        {/* {children} */}
        <BottomBar/>
        </body>
    </html>
    </ClerkProvider>
  )
}
